
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Sep 05 22:19:51 CST 2021
//----------------------------------------------------

package Analizafca;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Numero = 28;
  public static final int Globales = 2;
  public static final int GBarras = 3;
  public static final int REstadisticos = 31;
  public static final int Identificador = 29;
  public static final int Ruta = 30;
  public static final int DPuntos = 26;
  public static final int Titulo = 10;
  public static final int ParenC = 16;
  public static final int Coma = 25;
  public static final int GPie = 5;
  public static final int Double = 8;
  public static final int ParenA = 15;
  public static final int EjeX = 9;
  public static final int LlaveC = 18;
  public static final int LlaveA = 17;
  public static final int Compare = 6;
  public static final int Cadena = 27;
  public static final int TituloY = 13;
  public static final int EOF = 0;
  public static final int TituloX = 12;
  public static final int GLineas = 4;
  public static final int error = 1;
  public static final int Punto = 24;
  public static final int Archivo = 14;
  public static final int PComa = 23;
  public static final int Dolar = 22;
  public static final int Igual = 21;
  public static final int CorcheC = 20;
  public static final int CorcheA = 19;
  public static final int String = 7;
  public static final int Valores = 11;
}

