
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 02 16:06:07 CST 2021
//----------------------------------------------------

package Analizadores;

import java_cup.runtime.Symbol;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Thu Sep 02 16:06:07 CST 2021
  */
public class Sintac extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Sintac() {super();}

  /** Constructor which sets the default scanner. */
  public Sintac(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintac(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\057\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\003\006\000\002\003\007\000\002\005\004" +
    "\000\002\005\003\000\002\004\007\000\002\004\010\000" +
    "\002\004\007\000\002\004\011\000\002\004\007\000\002" +
    "\004\007\000\002\004\006\000\002\004\003\000\002\004" +
    "\005\000\002\004\003\000\002\006\003\000\002\006\004" +
    "\000\002\006\002\000\002\015\005\000\002\015\004\000" +
    "\002\021\006\000\002\017\005\000\002\017\005\000\002" +
    "\017\005\000\002\017\004\000\002\017\004\000\002\017" +
    "\005\000\002\017\003\000\002\017\003\000\002\017\003" +
    "\000\002\017\003\000\002\013\004\000\002\013\003\000" +
    "\002\013\004\000\002\012\005\000\002\012\005\000\002" +
    "\012\005\000\002\011\011\000\002\011\005\000\002\011" +
    "\002\000\002\016\004\000\002\010\004\000\002\010\005" +
    "\000\002\014\003\000\002\014\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\153\000\004\004\005\001\002\000\004\002\155\001" +
    "\002\000\004\046\010\001\002\000\006\002\uffff\004\005" +
    "\001\002\000\004\002\000\001\002\000\004\036\011\001" +
    "\002\000\026\005\023\006\016\007\017\011\022\012\025" +
    "\013\013\020\015\021\012\037\021\046\026\001\002\000" +
    "\004\034\057\001\002\000\004\040\132\001\002\000\004" +
    "\037\131\001\002\000\004\046\127\001\002\000\004\034" +
    "\057\001\002\000\004\034\057\001\002\000\026\005\ufff3" +
    "\006\ufff3\007\ufff3\011\ufff3\012\ufff3\013\ufff3\020\ufff3\021" +
    "\ufff3\037\ufff3\046\ufff3\001\002\000\006\002\ufffe\004\ufffe" +
    "\001\002\000\004\034\101\001\002\000\004\036\073\001" +
    "\002\000\026\005\023\006\016\007\017\011\022\012\025" +
    "\013\013\020\015\021\012\037\ufffb\046\026\001\002\000" +
    "\004\034\057\001\002\000\006\030\031\032\030\001\002" +
    "\000\026\005\ufff1\006\ufff1\007\ufff1\011\ufff1\012\ufff1\013" +
    "\ufff1\020\ufff1\021\ufff1\037\ufff1\046\ufff1\001\002\000\030" +
    "\005\uffd3\006\uffd3\007\uffd3\011\uffd3\012\uffd3\013\uffd3\020" +
    "\uffd3\021\uffd3\037\uffd3\042\046\046\uffd3\001\002\000\020" +
    "\024\035\027\036\033\040\034\033\044\041\045\032\047" +
    "\034\001\002\000\040\005\uffe4\006\uffe4\007\uffe4\011\uffe4" +
    "\012\uffe4\013\uffe4\020\uffe4\021\uffe4\025\uffe4\026\uffe4\027" +
    "\uffe4\035\uffe4\037\uffe4\042\uffe4\046\uffe4\001\002\000\020" +
    "\024\035\027\036\033\040\034\033\044\041\045\032\047" +
    "\034\001\002\000\040\005\uffe2\006\uffe2\007\uffe2\011\uffe2" +
    "\012\uffe2\013\uffe2\020\uffe2\021\uffe2\025\uffe2\026\uffe2\027" +
    "\uffe2\035\uffe2\037\uffe2\042\uffe2\046\uffe2\001\002\000\020" +
    "\024\035\027\036\033\040\034\033\044\041\045\032\047" +
    "\034\001\002\000\020\024\035\027\036\033\040\034\033" +
    "\044\041\045\032\047\034\001\002\000\036\005\uffd3\006" +
    "\uffd3\007\uffd3\011\uffd3\012\uffd3\013\uffd3\020\uffd3\021\uffd3" +
    "\025\045\026\044\027\043\037\uffd3\042\046\046\uffd3\001" +
    "\002\000\040\005\uffe1\006\uffe1\007\uffe1\011\uffe1\012\uffe1" +
    "\013\uffe1\020\uffe1\021\uffe1\025\uffe1\026\uffe1\027\uffe1\035" +
    "\uffe1\037\uffe1\042\uffe1\046\uffe1\001\002\000\040\005\uffe3" +
    "\006\uffe3\007\uffe3\011\uffe3\012\uffe3\013\uffe3\020\uffe3\021" +
    "\uffe3\025\uffe3\026\uffe3\027\uffe3\035\uffe3\037\uffe3\042\uffe3" +
    "\046\uffe3\001\002\000\026\005\uffeb\006\uffeb\007\uffeb\011" +
    "\uffeb\012\uffeb\013\uffeb\020\uffeb\021\uffeb\037\uffeb\046\uffeb" +
    "\001\002\000\020\024\035\027\036\033\040\034\033\044" +
    "\041\045\032\047\034\001\002\000\020\024\035\027\036" +
    "\033\040\034\033\044\041\045\032\047\034\001\002\000" +
    "\020\024\035\027\036\033\040\034\033\044\041\045\032" +
    "\047\034\001\002\000\026\005\uffd4\006\uffd4\007\uffd4\011" +
    "\uffd4\012\uffd4\013\uffd4\020\uffd4\021\uffd4\037\uffd4\046\uffd4" +
    "\001\002\000\040\005\uffe8\006\uffe8\007\uffe8\011\uffe8\012" +
    "\uffe8\013\uffe8\020\uffe8\021\uffe8\025\uffe8\026\uffe8\027\uffe8" +
    "\035\uffe8\037\uffe8\042\uffe8\046\uffe8\001\002\000\040\005" +
    "\uffea\006\uffea\007\uffea\011\uffea\012\uffea\013\uffea\020\uffea" +
    "\021\uffea\025\045\026\uffea\027\uffea\035\uffea\037\uffea\042" +
    "\uffea\046\uffea\001\002\000\040\005\uffe9\006\uffe9\007\uffe9" +
    "\011\uffe9\012\uffe9\013\uffe9\020\uffe9\021\uffe9\025\045\026" +
    "\uffe9\027\uffe9\035\uffe9\037\uffe9\042\uffe9\046\uffe9\001\002" +
    "\000\040\005\uffe7\006\uffe7\007\uffe7\011\uffe7\012\uffe7\013" +
    "\uffe7\020\uffe7\021\uffe7\025\045\026\uffe7\027\uffe7\035\uffe7" +
    "\037\uffe7\042\uffe7\046\uffe7\001\002\000\040\005\uffe6\006" +
    "\uffe6\007\uffe6\011\uffe6\012\uffe6\013\uffe6\020\uffe6\021\uffe6" +
    "\025\045\026\044\027\043\035\uffe6\037\uffe6\042\uffe6\046" +
    "\uffe6\001\002\000\012\025\045\026\044\027\043\035\055" +
    "\001\002\000\040\005\uffe5\006\uffe5\007\uffe5\011\uffe5\012" +
    "\uffe5\013\uffe5\020\uffe5\021\uffe5\025\uffe5\026\uffe5\027\uffe5" +
    "\035\uffe5\037\uffe5\042\uffe5\046\uffe5\001\002\000\026\005" +
    "\ufff2\006\ufff2\007\ufff2\011\ufff2\012\ufff2\013\ufff2\020\ufff2" +
    "\021\ufff2\037\ufff2\046\ufff2\001\002\000\022\024\035\027" +
    "\036\033\040\034\033\035\067\044\041\045\032\047\034" +
    "\001\002\000\004\036\061\001\002\000\030\005\023\006" +
    "\016\007\017\011\022\012\025\013\013\017\063\020\015" +
    "\021\012\037\uffee\046\026\001\002\000\004\037\ufff0\001" +
    "\002\000\006\037\uffd3\042\046\001\002\000\004\037\065" +
    "\001\002\000\026\005\ufffa\006\ufffa\007\ufffa\011\ufffa\012" +
    "\ufffa\013\ufffa\020\ufffa\021\ufffa\037\ufffa\046\ufffa\001\002" +
    "\000\004\037\uffef\001\002\000\032\005\uffd6\006\uffd6\007" +
    "\uffd6\011\uffd6\012\uffd6\013\uffd6\020\uffd6\021\uffd6\036\uffd6" +
    "\037\uffd6\042\uffd6\046\uffd6\001\002\000\012\025\045\026" +
    "\044\027\043\035\071\001\002\000\032\005\uffd5\006\uffd5" +
    "\007\uffd5\011\uffd5\012\uffd5\013\uffd5\020\uffd5\021\uffd5\036" +
    "\uffd5\037\uffd5\042\uffd5\046\uffd5\001\002\000\004\037\ufffc" +
    "\001\002\000\030\005\023\006\016\007\017\011\022\012" +
    "\025\013\013\017\063\020\015\021\012\037\uffee\046\026" +
    "\001\002\000\004\037\075\001\002\000\004\006\076\001" +
    "\002\000\004\034\057\001\002\000\004\042\100\001\002" +
    "\000\026\005\ufff7\006\ufff7\007\ufff7\011\ufff7\012\ufff7\013" +
    "\ufff7\020\ufff7\021\ufff7\037\ufff7\046\ufff7\001\002\000\004" +
    "\035\102\001\002\000\030\005\uffd3\006\uffd3\007\uffd3\011" +
    "\uffd3\012\uffd3\013\uffd3\020\uffd3\021\uffd3\037\uffd3\042\046" +
    "\046\uffd3\001\002\000\026\005\ufff4\006\ufff4\007\ufff4\011" +
    "\ufff4\012\ufff4\013\ufff4\020\ufff4\021\ufff4\037\ufff4\046\ufff4" +
    "\001\002\000\004\036\105\001\002\000\030\005\023\006" +
    "\016\007\017\011\022\012\025\013\013\017\063\020\015" +
    "\021\012\037\uffee\046\026\001\002\000\004\037\107\001" +
    "\002\000\030\005\uffd8\006\uffd8\007\uffd8\010\111\011\uffd8" +
    "\012\uffd8\013\uffd8\020\uffd8\021\uffd8\037\uffd8\046\uffd8\001" +
    "\002\000\026\005\ufff9\006\ufff9\007\ufff9\011\ufff9\012\ufff9" +
    "\013\ufff9\020\ufff9\021\ufff9\037\ufff9\046\ufff9\001\002\000" +
    "\006\007\113\036\112\001\002\000\004\037\121\001\002" +
    "\000\004\034\114\001\002\000\004\035\115\001\002\000" +
    "\004\036\116\001\002\000\004\037\117\001\002\000\030" +
    "\005\uffd8\006\uffd8\007\uffd8\010\111\011\uffd8\012\uffd8\013" +
    "\uffd8\020\uffd8\021\uffd8\037\uffd8\046\uffd8\001\002\000\026" +
    "\005\uffda\006\uffda\007\uffda\011\uffda\012\uffda\013\uffda\020" +
    "\uffda\021\uffda\037\uffda\046\uffda\001\002\000\026\005\uffd9" +
    "\006\uffd9\007\uffd9\011\uffd9\012\uffd9\013\uffd9\020\uffd9\021" +
    "\uffd9\037\uffd9\046\uffd9\001\002\000\004\036\123\001\002" +
    "\000\030\005\023\006\016\007\017\011\022\012\025\013" +
    "\013\017\063\020\015\021\012\037\uffee\046\026\001\002" +
    "\000\004\037\125\001\002\000\026\005\ufff8\006\ufff8\007" +
    "\ufff8\011\ufff8\012\ufff8\013\ufff8\020\ufff8\021\ufff8\037\ufff8" +
    "\046\ufff8\001\002\000\026\005\uffec\006\uffec\007\uffec\011" +
    "\uffec\012\uffec\013\uffec\020\uffec\021\uffec\037\uffec\046\uffec" +
    "\001\002\000\032\005\uffd3\006\uffd3\007\uffd3\011\uffd3\012" +
    "\uffd3\013\uffd3\020\uffd3\021\uffd3\030\031\037\uffd3\042\046" +
    "\046\uffd3\001\002\000\026\005\uffed\006\uffed\007\uffed\011" +
    "\uffed\012\uffed\013\uffed\020\uffed\021\uffed\037\uffed\046\uffed" +
    "\001\002\000\006\002\ufffd\004\ufffd\001\002\000\004\014" +
    "\133\001\002\000\004\034\057\001\002\000\030\005\uffd3" +
    "\006\uffd3\007\uffd3\011\uffd3\012\uffd3\013\uffd3\020\uffd3\021" +
    "\uffd3\037\uffd3\042\046\046\uffd3\001\002\000\026\005\ufff5" +
    "\006\ufff5\007\ufff5\011\ufff5\012\ufff5\013\ufff5\020\ufff5\021" +
    "\ufff5\037\ufff5\046\ufff5\001\002\000\004\036\137\001\002" +
    "\000\006\015\140\016\141\001\002\000\004\043\154\001" +
    "\002\000\010\044\150\045\146\047\147\001\002\000\004" +
    "\037\145\001\002\000\010\015\140\016\141\037\uffdf\001" +
    "\002\000\004\037\uffe0\001\002\000\026\005\ufff6\006\ufff6" +
    "\007\ufff6\011\ufff6\012\ufff6\013\ufff6\020\ufff6\021\ufff6\037" +
    "\ufff6\046\ufff6\001\002\000\004\043\153\001\002\000\004" +
    "\043\152\001\002\000\004\043\151\001\002\000\010\015" +
    "\uffdd\016\uffdd\037\uffdd\001\002\000\010\015\uffdc\016\uffdc" +
    "\037\uffdc\001\002\000\010\015\uffdb\016\uffdb\037\uffdb\001" +
    "\002\000\004\037\uffde\001\002\000\004\002\001\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\153\000\006\002\003\003\005\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\002\006\003\005\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\004\023\005" +
    "\013\015\017\021\026\001\001\000\004\010\135\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\021\125\001" +
    "\001\000\004\010\121\001\001\000\004\010\103\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\004\023\005\071\015\017\021\026" +
    "\001\001\000\004\010\057\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\014\055\001\001\000\004\017\036" +
    "\001\001\000\002\001\001\000\004\017\053\001\001\000" +
    "\002\001\001\000\004\017\052\001\001\000\004\017\051" +
    "\001\001\000\004\014\041\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\017\050\001\001" +
    "\000\004\017\047\001\001\000\004\017\046\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\017\067" +
    "\001\001\000\002\001\001\000\014\004\023\005\061\006" +
    "\063\015\017\021\026\001\001\000\002\001\001\000\004" +
    "\014\065\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\004\023\005\061\006" +
    "\073\015\017\021\026\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\010\076\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\014\102\001\001" +
    "\000\002\001\001\000\002\001\001\000\014\004\023\005" +
    "\061\006\105\015\017\021\026\001\001\000\002\001\001" +
    "\000\004\011\107\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\011\117\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\014\004\023\005\061\006\123\015\017\021\026\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\014\127\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\010\133\001\001\000\004" +
    "\014\134\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\012\142\013\141\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\012\142\013\143\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintac$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintac$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintac$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private Symbol s;
    public void syntax_error(Symbol s){
        this.s = s;
        System.out.println(s.value.toString());
    }

    public Symbol getS(){
        return this.s;
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Sintac$actions {
  private final Sintac parser;

  /** Constructor */
  CUP$Sintac$actions(Sintac parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Sintac$do_action(
    int                        CUP$Sintac$act_num,
    java_cup.runtime.lr_parser CUP$Sintac$parser,
    java.util.Stack            CUP$Sintac$stack,
    int                        CUP$Sintac$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintac$result;

      /* select the action based on the action number */
      switch (CUP$Sintac$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // FINEXPRE ::= 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("FINEXPRE",10, ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // FINEXPRE ::= PComa 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("FINEXPRE",10, ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // PARENTESIS ::= ParenA EXPRESIONES ParenC 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("PARENTESIS",6, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-2)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // PARENTESIS ::= ParenA ParenC 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("PARENTESIS",6, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-1)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // REQUIRE ::= Require PARENTESIS 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("REQUIRE",12, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-1)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // ELSE ::= 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("ELSE",7, ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // ELSE ::= Else LlaveA LlaveC 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("ELSE",7, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-2)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // ELSE ::= Else If ParenA ParenC LlaveA LlaveC ELSE 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("ELSE",7, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-6)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // CASE ::= Case Numero DPuntos 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("CASE",8, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-2)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // CASE ::= Case Char DPuntos 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("CASE",8, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-2)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // CASE ::= Case Cadena DPuntos 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("CASE",8, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-2)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // CASES ::= Default DPuntos 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("CASES",9, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-1)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // CASES ::= CASE 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("CASES",9, ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // CASES ::= CASE CASES 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("CASES",9, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-1)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // EXPRESIONES ::= Bool 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("EXPRESIONES",13, ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // EXPRESIONES ::= Char 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("EXPRESIONES",13, ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // EXPRESIONES ::= Cadena 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("EXPRESIONES",13, ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // EXPRESIONES ::= Numero 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("EXPRESIONES",13, ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // EXPRESIONES ::= ParenA EXPRESIONES ParenC 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("EXPRESIONES",13, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-2)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // EXPRESIONES ::= Not EXPRESIONES 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("EXPRESIONES",13, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-1)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // EXPRESIONES ::= Resta EXPRESIONES 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("EXPRESIONES",13, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-1)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // EXPRESIONES ::= EXPRESIONES Matematico EXPRESIONES 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("EXPRESIONES",13, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-2)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // EXPRESIONES ::= EXPRESIONES Resta EXPRESIONES 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("EXPRESIONES",13, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-2)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // EXPRESIONES ::= EXPRESIONES Suma EXPRESIONES 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("EXPRESIONES",13, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-2)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // ASIGNACION ::= Identificador Igual EXPRESIONES FINEXPRE 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("ASIGNACION",15, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-3)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // DECLARA ::= Variable ASIGNACION 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("DECLARA",11, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-1)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // DECLARA ::= Variable Identificador FINEXPRE 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("DECLARA",11, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-2)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // INSTRUCCIONES ::= 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",4, ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // INSTRUCCIONES ::= Break FINEXPRE 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",4, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-1)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // INSTRUCCIONES ::= SENTENCIAS 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",4, ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // SENTENCIA ::= ASIGNACION 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // SENTENCIA ::= Identificador Incremento FINEXPRE 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-2)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // SENTENCIA ::= DECLARA 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // SENTENCIA ::= Llamada ParenA ParenC FINEXPRE 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-3)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // SENTENCIA ::= Console Punto Log PARENTESIS FINEXPRE 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-4)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // SENTENCIA ::= Switch PARENTESIS LlaveA CASES LlaveC 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-4)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // SENTENCIA ::= Do LlaveA INSTRUCCIONES LlaveC While PARENTESIS PComa 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-6)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // SENTENCIA ::= While PARENTESIS LlaveA INSTRUCCIONES LlaveC 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-4)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // SENTENCIA ::= If PARENTESIS LlaveA INSTRUCCIONES LlaveC ELSE 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-5)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // SENTENCIA ::= For PARENTESIS LlaveA INSTRUCCIONES LlaveC 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-4)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // SENTENCIAS ::= SENTENCIA 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("SENTENCIAS",3, ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // SENTENCIAS ::= SENTENCIA SENTENCIAS 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("SENTENCIAS",3, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-1)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // INI ::= Clase Identificador LlaveA SENTENCIAS LlaveC 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("INI",1, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-4)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // INI ::= Clase Identificador LlaveA LlaveC 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("INI",1, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-3)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INIS ::= INI 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("INIS",0, ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INIS ::= INI INIS 
            {
              Object RESULT =null;

              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("INIS",0, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-1)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          return CUP$Sintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INIS EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintac$stack.elementAt(CUP$Sintac$top-1)).value;
		RESULT = start_val;
              CUP$Sintac$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintac$stack.elementAt(CUP$Sintac$top-1)), ((java_cup.runtime.Symbol)CUP$Sintac$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintac$parser.done_parsing();
          return CUP$Sintac$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

