
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 04 10:01:07 CST 2021
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Require = 16;
  public static final int Incremento = 24;
  public static final int Coma = 31;
  public static final int If = 5;
  public static final int PComa = 32;
  public static final int LlaveC = 29;
  public static final int Clase = 2;
  public static final int LlaveA = 28;
  public static final int Default = 11;
  public static final int Llamada = 7;
  public static final int Else = 6;
  public static final int Variable = 14;
  public static final int ParenC = 27;
  public static final int Break = 13;
  public static final int ParenA = 26;
  public static final int Matematico = 19;
  public static final int Punto = 30;
  public static final int Relacionales = 23;
  public static final int Console = 9;
  public static final int While = 4;
  public static final int Cadena = 34;
  public static final int For = 8;
  public static final int EOF = 0;
  public static final int Logico = 17;
  public static final int Not = 18;
  public static final int error = 1;
  public static final int Switch = 15;
  public static final int Char = 37;
  public static final int Do = 3;
  public static final int Case = 12;
  public static final int DPuntos = 33;
  public static final int Identificador = 36;
  public static final int Resta = 21;
  public static final int Bool = 25;
  public static final int Log = 10;
  public static final int Numero = 35;
  public static final int Suma = 20;
  public static final int Igual = 22;
}

