
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Aug 31 22:32:50 CST 2021
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 6;
  public static final int Clase = 2;
  public static final int For = 9;
  public static final int Numero = 32;
  public static final int Relacionales = 20;
  public static final int Console = 13;
  public static final int Break = 11;
  public static final int Identificador = 33;
  public static final int DPuntos = 30;
  public static final int Default = 15;
  public static final int ParenC = 24;
  public static final int Logico = 17;
  public static final int Coma = 28;
  public static final int ParenA = 23;
  public static final int LlaveC = 26;
  public static final int Matematico = 18;
  public static final int LlaveA = 25;
  public static final int Cadena = 31;
  public static final int EOF = 0;
  public static final int Llamada = 8;
  public static final int Log = 14;
  public static final int Case = 16;
  public static final int If = 5;
  public static final int Bool = 22;
  public static final int error = 1;
  public static final int Variable = 7;
  public static final int Punto = 27;
  public static final int Switch = 10;
  public static final int PComa = 29;
  public static final int Do = 3;
  public static final int Igual = 19;
  public static final int While = 4;
  public static final int Require = 12;
  public static final int Incremento = 21;
}

